package dev.java.record;

public class RecordDemo {
    public static record Employee(Integer id,String name, String email) {
        /**
         * - all boilerplate code is auto generated
         * - records are immutable in nature
         * - final type - cannot be inherited
         * - cannot extend a class
         * - can implement an interface
         * - all-args constructor is auto generated
         * - getters() generated
         * - no setters()
         * - toString(), equals(), hash() auto generated
         *
         */

    }

    public static void main(String args[]){

        // all-args constructor is auto generated
        Employee employee = new Employee(1,"merry", "merry@java.dev");

        // autogenerate toString method
        System.out.println(employee);

        // autogenerated getter
        System.out.println(employee.id());
        System.out.println(employee.name());
        System.out.println(employee.email());


    }

}
